// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEPEQmiZ0_UWDsDk0fkyVWuxKGZFnH3dY',
    appId: '1:313890363446:web:84ef73f2936db383d36097',
    messagingSenderId: '313890363446',
    projectId: 'photobooth-b27d7',
    authDomain: 'photobooth-b27d7.firebaseapp.com',
    storageBucket: 'photobooth-b27d7.appspot.com',
    measurementId: 'G-4WCZT9496W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7pv-WCCJe6mhEMB0HmQaQ1S9C2JwbDAQ',
    appId: '1:313890363446:android:f6faad1e71c3794ed36097',
    messagingSenderId: '313890363446',
    projectId: 'photobooth-b27d7',
    storageBucket: 'photobooth-b27d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS5aL2QayLF7rodNUgv9J4OLJR_IDWP1I',
    appId: '1:313890363446:ios:06b3293aada307cad36097',
    messagingSenderId: '313890363446',
    projectId: 'photobooth-b27d7',
    storageBucket: 'photobooth-b27d7.appspot.com',
    iosBundleId: 'com.third.flutter3photobooth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS5aL2QayLF7rodNUgv9J4OLJR_IDWP1I',
    appId: '1:313890363446:ios:8e2ecf923a4eab14d36097',
    messagingSenderId: '313890363446',
    projectId: 'photobooth-b27d7',
    storageBucket: 'photobooth-b27d7.appspot.com',
    iosBundleId: 'com.example.flutter3photobooth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARJSFOWlPqJzzUHvKYTYTl5oNPFOp8O9s',
    appId: '1:313890363446:web:fd34ac46b37b2a85d36097',
    messagingSenderId: '313890363446',
    projectId: 'photobooth-b27d7',
    authDomain: 'photobooth-b27d7.firebaseapp.com',
    storageBucket: 'photobooth-b27d7.appspot.com',
    measurementId: 'G-K6BZXFYXK1',
  );
}
